[build.environment]
  BUNDLER_VERSION = "2.4.22"
  RUBY_VERSION = "2.7.8"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000"
    X-Frame-Options = "DENY"